[package]
name = "giga"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = "symbols"

[dependencies]
ratatui = "0.26"
libc = "0.2"
ropey = "1.6.1"
git2 = "0.18.3"
crossterm = "0.27.0"
